### ISSUE TITLE
City/Name filter

### ISSUE THREAD

**Issue by vladkampov** [iuriizaporozhets/job-applicants-status#1]
- Filter can't be used with name/city with a capital letter. (i.e. Lola/lola/LOLA)
- Filter can't be used with a full name (i.e. Lola Shaw)
- City filter is pointless due to now city rendered at all

**Comment by iuriizaporozhets** [comment]
Will be fixed.

**Comment by iuriizaporozhets** [comment]
For now all the described filtering variants work fine.
